"""Initial schema

Revision ID: da1ba2ea848f
Revises: 
Create Date: 2026-01-04 15:13:44.218065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1ba2ea848f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=False),
    sa.Column('standard_currency', sa.String(), nullable=False),
    sa.Column('company_number', sa.String(), nullable=True),
    sa.Column('vat_number', sa.String(), nullable=True),
    sa.Column('tax_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('von', sa.String(), nullable=False),
    sa.Column('nach', sa.String(), nullable=False),
    sa.Column('kurs', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('nummer', sa.String(), nullable=False),
    sa.Column('monat', sa.String(), nullable=False),
    sa.Column('kunde_id', sa.Integer(), nullable=False),
    sa.Column('gesamtbetrag', sa.Numeric(), nullable=True),
    sa.Column('zielwaehrung', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['kunde_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('invoice_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('beschreibung', sa.String(), nullable=False),
    sa.Column('menge', sa.Numeric(), nullable=False),
    sa.Column('einzelpreis', sa.Numeric(), nullable=False),
    sa.Column('waehrung', sa.String(), nullable=False),
    sa.Column('attachment_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_position')
    op.drop_table('invoice')
    op.drop_table('exchange_rate')
    op.drop_table('customer')
    # ### end Alembic commands ###
