"""add position_template

Revision ID: e9c28b5cf601
Revises: c02736daea2a
Create Date: 2026-01-04 18:11:12.323967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c28b5cf601'
down_revision: Union[str, Sequence[str], None] = 'c02736daea2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('beschreibung', sa.String(), nullable=False),
    sa.Column('standard_menge', sa.Numeric(), nullable=False),
    sa.Column('einzelpreis', sa.Numeric(), nullable=False),
    sa.Column('waehrung', sa.String(), nullable=False),
    sa.Column('attachment_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_template')
    # ### end Alembic commands ###
